PawGuide.Web/PawGuide.Web/Areas/Publications/Models/Articles/ArticleListingViewModel.cs
namespace PawGuide.Web.Areas.Publications.Models.Articles
{
    using Services.Publications.Models;
    using System.Collections.Generic;

    public class ArticleListingViewModel : Pager
    {
        public IEnumerable<ArticleListingServiceModel> Articles { get; set; }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Publications/Controllers/ArticlesController.cs
namespace PawGuide.Web.Areas.Publications.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Models.Articles;
    using Services.Publications;
    using Services.Html;
    using System.Threading.Tasks;
    using Services.Publications.Models;

    using static WebConstants;

    [Area(PublicationsArea)]
    [Authorize(Roles = "Administrator, Moderator")]
    public class ArticlesController : Controller
    {
        private readonly IPublicationService publications;
        private readonly UserManager<User> userManager;
        private readonly IHtmlService html;

        public ArticlesController(
            IPublicationService publications,
            UserManager<User> userManager,
            IHtmlService html)
        {
            this.publications = publications;
            this.userManager = userManager;
            this.html = html;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int page = 1)
            => View(new ArticleListingViewModel
            {
                Articles = await this.publications.AllArticlesAsync(page),
                TotalPublications = await this.publications.TotalAsync(),
                CurrentPage = page
            });

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
            => this.ViewOrNotFound(await this.publications.ArticleById(id));

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Create(PublicationsFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Content = this.html.Sanitize(model.Content);

            var userId = this.userManager.GetUserId(User);

            await this.publications.CreateAsync(model.Title, model.Content, userId);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var articleExists = await this.publications.Exists(id);

            if (!articleExists)
            {
                return NotFound();
            }

            return this.ViewOrNotFound(await this.publications.ArticleById(id));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ArticleDetailsServiceModel articleModel)
        {
            if (!ModelState.IsValid)
            {
                return View(articleModel);
            }

            var userId = this.userManager.GetUserId(User);

            var update = await this.publications.EditAsync(
                id,
                articleModel.Title,
                articleModel.Content,
                articleModel.PicUrl,
                userId);

            if (!update == null)
            {
                return NotFound();
            }

            this.TempData.AddWarningMessage(string.Format(SuccessfullEdit, articleModel.Title));


            return RedirectToAction(nameof(Index));
        }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Articles/Create.cshtml
@model PublicationsFormModel
@{
    ViewData["Title"] = "Publish Article";
}

@await Html.PartialAsync("_HeadingPartial")

<script src="https://cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>

<div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        
        @await Html.PartialAsync("_PublicationsFormPartial")

    </div>
    <div class="col-md-2"></div>
</div>
<script>
    CKEDITOR.replace('Content');
</script>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

}

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Articles/Details.cshtml
@using PawGuide.Web
@model ArticleDetailsServiceModel
@{
    ViewData["Title"] = Model.Title;
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li>
                        <a asp-area="Publications" asp-controller="Articles" asp-action="Index">Articles</a>
                    </li>
                    <li>@ViewData["Title"]</li>
                </ul>

            </div>
        </div>
    </div>
</div>

<div id="content">
    <div class="container">

        <div class="row">
            <!-- *** LEFT COLUMN ***
            _________________________________________________________ -->

            <div class="col-md-9" id="blog-post">

                <p class="text-muted text-uppercase mb-small text-right">
                    <em>By @Model.Author | @Model.PublishDate.ToShortDateString()</em>
                </p>

                <div id="post-content">
                    

                    <p  class="text-center">
                        <img src="@Model.PicUrl" alt="Sample Image" width="300px" />
                    </p>

                    <h2>@ViewData["Title"]</h2>

                    @Html.Raw(Model.Content)
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            @if (User.IsInRole(WebConstants.ModeratorRole) || User.IsInRole(WebConstants.AdministratorRole))
                            {
                                <a class="btn btn-template-main" asp-area="Publications" asp-controller="Articles" asp-action="Edit" asp-route-id="@Model.Id" asp-route-title="@Model.Title.ToFriendlyUrl()">Edit</a>
                            }
                        </div>
                    </div>
                </div>
                <!-- /#post-content -->

                <div id="comments">
                    <h4 class="text-uppercase">2 comments</h4>


                    <div class="row comment">
                        <div class="col-sm-3 col-md-2 text-center-xs">
                            <p>
                                <img src="img/blog-avatar2.jpg" class="img-responsive img-circle" alt="">
                            </p>
                        </div>
                        <div class="col-sm-9 col-md-10">
                            <h5 class="text-uppercase">Julie Alma</h5>
                            <p class="posted">
                                <i class="fa fa-clock-o"></i> September 23, 2011 at 12:00 am
                            </p>
                            <p>
                                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                            </p>
                            <p class="reply">
                                <a href="#"><i class="fa fa-reply"></i> Reply</a>
                            </p>
                        </div>
                    </div>
                    <!-- /.comment -->


                    <div class="row comment last">

                        <div class="col-sm-3 col-md-2 text-center-xs">
                            <p>
                                <img src="img/blog-avatar.jpg" class="img-responsive img-circle" alt="">
                            </p>
                        </div>

                        <div class="col-sm-9 col-md-10">
                            <h5 class="text-uppercase">Louise Armero</h5>
                            <p class="posted">
                                <i class="fa fa-clock-o"></i> September 23, 2012 at 12:00 am
                            </p>
                            <p>
                                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                            </p>
                            <p class="reply">
                                <a href="#"><i class="fa fa-reply"></i> Reply</a>
                            </p>
                        </div>

                    </div>
                    <!-- /.comment -->
                </div>
                <!-- /#comments -->


                <div id="comment-form">

                    <h4 class="text-uppercase">Leave comment</h4>

                    <form>
                        <div class="row">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name">
                                        Name <span class="required">*</span>
                                    </label>
                                    <input type="text" class="form-control" id="name">
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">
                                        Email <span class="required">*</span>
                                    </label>
                                    <input type="text" class="form-control" id="email">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="comment">
                                        Comment <span class="required">*</span>
                                    </label>
                                    <textarea class="form-control" id="comment" rows="4"></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 text-right">
                                <button class="btn btn-template-main"><i class="fa fa-comment-o"></i> Post comment</button>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- /#comment-form -->

            </div>
            <!-- /#blog-post -->
            <!-- *** LEFT COLUMN END *** -->

        </div>
    </div>
</div>

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Articles/Edit.cshtml
@model ArticleDetailsServiceModel

@{
    ViewData["Title"] = "Edit Article";
}

@await Html.PartialAsync("_HeadingPartial")

<script src="https://cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>

<div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form method="post">
            <h3>Edit This Article</h3>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicUrl"></label>
                <input asp-for="PicUrl" class="form-control" />
                <span asp-validation-for="PicUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" rows="30" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
<script>
    CKEDITOR.replace('Content');
</script>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

}

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Articles/Index.cshtml
@model ArticleListingViewModel
@{
    ViewData["Title"] = "Helpful Articles";
}
@await Html.PartialAsync("_HeadingPartial")

<div id="content">
    <div class="container">
        <div class="row">
            <!-- *** LEFT COLUMN ***
            _________________________________________________________ -->

            <div class="col-md-9" id="blog-listing-medium">
                @foreach (var article in Model.Articles)
                {
                    <section class="post">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="image">
                                    <a asp-action="Details" asp-route-id="@article.Id" asp-route-title="@article.Title.ToFriendlyUrl()">
                                        <img src="@article.PicUrl" class="img-responsive" alt="Example blog post alt">
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2>
                                    <a asp-action="Details" asp-route-id="@article.Id" asp-route-title="@article.Title.ToFriendlyUrl()">
                                        @article.Title
                                    </a>
                                </h2>
                                <div class="clearfix">
                                    <p class="author-category">
                                        By @article.Author
                                    </p>
                                    <p class="date-comments">
                                        <a href="blog-post.html"><i class="fa fa-calendar-o"></i>@article.PublishDate.ToShortDateString()</a>
                                        <a href="blog-post.html"><i class="fa fa-comment-o"></i> 8 Comments</a>
                                    </p>
                                </div>
                                <p class="intro">
                                    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                    Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                                </p>
                                <p class="read-more">
                                    <a asp-action="Details" asp-route-id="@article.Id" asp-route-title="@article.Title.ToFriendlyUrl()" class="btn btn-template-main">Continue reading</a>
                                </p>
                            </div>
                        </div>
                    </section>
                }

                @if (Model.TotalPublications > Model.Articles.Count())
                {
                    <ul class="pager">
                        <li class="@(Model.CurrentPage == 1 ? "disabled" : string.Empty)">
                            <a asp-route-page="@Model.PreviousPage" aria-label="Previous">
                                <span aria-hidden="true">
                                    &larr; Older
                                </span>
                            </a>
                        </li>
                        <li class="@(Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty)">
                            <a asp-route-page="@Model.NextPage" aria-label="Next">
                                <span aria-hidden="true">
                                    Newer &rarr;
                                </span>
                            </a>
                        </li>
                    </ul>
                }
            </div>

            <!-- *** LEFT COLUMN END *** -->
        </div>
    </div>
</div>