PawGuide.Web/PawGuide.Web/Areas/Publications/Models/Ads/AdListingViewModel.cs
namespace PawGuide.Web.Areas.Publications.Models.Ads
{
    using System;
    using System.Collections.Generic;
    using PawGuide.Services;
    using PawGuide.Services.Publications.Models;

    public class AdListingViewModel : Pager
    {
        public IEnumerable<AdListingServiceModel> Ads { get; set; }

    }
}

PawGuide.Web/PawGuide.Web/Areas/Publications/Models/Ads/PublishAdFormModel.cs
namespace PawGuide.Web.Areas.Publications.Models.Ads
{
    using System.ComponentModel.DataAnnotations;

    using static Data.DataConstants;

    public class PublishAdFormModel
    {
        [Required]
        [MinLength(PublicationTitleMinLength)]
        [MaxLength(PublicationTitleMaxLength)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [MinLength(PicUrlMinLength)]
        [MaxLength(PicUrlMaxLength)]
        public string PicUrl { get; set; }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Publications/Controllers/AdsController.cs
namespace PawGuide.Web.Areas.Publications.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Data.Models;
    using Services.Html;
    using Services.Publications;
    using Services.Publications.Models;
    using Models;
    using Models.Ads;
    using Infrastructure.Filters;
    using Infrastructure.Extensions;

    using static WebConstants;

    [Area(PublicationsArea)]
    [Authorize]
    public class AdsController : Controller
    {
        private readonly IPublicationService publications;
        private readonly UserManager<User> userManager;
        private readonly IHtmlService html;

        public AdsController(
            IPublicationService publications,
            UserManager<User> userManager,
            IHtmlService html)
        {
            this.publications = publications;
            this.userManager = userManager;
            this.html = html;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int page = 1)
            => View(new AdListingViewModel
            {
                Ads = await this.publications.AllAdsAsync(page),
                TotalPublications = await this.publications.TotalAsync(),
                CurrentPage = page
            });

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
            => this.ViewOrNotFound(await this.publications.AdById(id));

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Create(PublicationsFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Content = this.html.Sanitize(model.Content);

            var userId = this.userManager.GetUserId(User);

            var isApproved = false;

            await this.publications.CreateAsync(
                model.Title,
                model.Content,
                model.PicUrl,
                isApproved,
                userId);

            this.TempData.AddSuccessMessage(string.Format(SuccessfullAdd, model.Title));


            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var adExists = await this.publications.Exists(id);

            if (!adExists)
            {
                return NotFound();
            }

            return this.ViewOrNotFound(await this.publications.AdById(id));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, AdDetailsServiceModel adModel)
        {
            if (!ModelState.IsValid)
            {
                return View(adModel);
            }

            var userId = this.userManager.GetUserId(User);

            var update = await this.publications.EditAsync(
                id,
                adModel.Title,
                adModel.Content,
                adModel.PicUrl,
                adModel.IsApproved,
                userId);

            if (!update == null)
            {
                return NotFound();
            }
            this.TempData.AddWarningMessage(string.Format(SuccessfullEdit, adModel.Title));

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ForApproval(int page = 1)
            => View(new AdListingViewModel
            {
                Ads = await this.publications.AllAdsAsync(page),
                TotalPublications = await this.publications.TotalAsync(),
                CurrentPage = page
            });
    }
}

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Ads/Create.cshtml
@model PublicationsFormModel
@{
    ViewData["Title"] = "Publish Ad";
}

@await Html.PartialAsync("_HeadingPartial")

<script src="https://cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>

<div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        
        @await Html.PartialAsync("_PublicationsFormPartial")

    </div>
    <div class="col-md-2"></div>
</div>
<script>
    CKEDITOR.replace('Content');
</script>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

}

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Ads/Details.cshtml
@using PawGuide.Web
@model AdDetailsServiceModel
@{
    ViewData["Title"] = Model.Title;
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li>
                        <a asp-area="Publications" asp-controller="Ads" asp-action="Index">Ads</a>
                    </li>
                    <li>@ViewData["Title"]</li>
                </ul>

            </div>
        </div>
    </div>
</div>


<div id="content">
    <div class="container">

        <div class="row">
            <!-- *** LEFT COLUMN ***
            _________________________________________________________ -->

            <div class="col-md-9" id="blog-post">
                <div id="post-content">
                    <p class="text-center">
                        <img src="@Model.PicUrl" alt="Sample Image" width="300px" />
                    </p>
                    <h2>@ViewData["Title"]</h2>
                    @Html.Raw(Model.Content)
                    <p class="text-muted text-uppercase mb-small text-right">
                        <em>By @Model.Author | @Model.PublishDate.ToShortDateString()</em>
                    </p>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            @if (User.IsInRole(WebConstants.ModeratorRole) || User.IsInRole(WebConstants.AdministratorRole))
                            {
                                <a class="btn btn-template-main" asp-area="Publications" asp-controller="Ads" asp-action="Edit" asp-route-id="@Model.Id" asp-route-title="@Model.Title.ToFriendlyUrl()">Edit</a>
                            }
                        </div>
                    </div>
                </div>
                <!-- /#post-content -->

                <div id="comments">
                    <h4 class="text-uppercase">2 comments</h4>


                    <div class="row comment">
                        <div class="col-sm-3 col-md-2 text-center-xs">
                            <p>
                                <img src="img/blog-avatar2.jpg" class="img-responsive img-circle" alt="">
                            </p>
                        </div>
                        <div class="col-sm-9 col-md-10">
                            <h5 class="text-uppercase">Julie Alma</h5>
                            <p class="posted">
                                <i class="fa fa-clock-o"></i> September 23, 2011 at 12:00 am
                            </p>
                            <p>
                                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                            </p>
                            <p class="reply">
                                <a href="#"><i class="fa fa-reply"></i> Reply</a>
                            </p>
                        </div>
                    </div>
                    <!-- /.comment -->


                    <div class="row comment last">

                        <div class="col-sm-3 col-md-2 text-center-xs">
                            <p>
                                <img src="img/blog-avatar.jpg" class="img-responsive img-circle" alt="">
                            </p>
                        </div>

                        <div class="col-sm-9 col-md-10">
                            <h5 class="text-uppercase">Louise Armero</h5>
                            <p class="posted">
                                <i class="fa fa-clock-o"></i> September 23, 2012 at 12:00 am
                            </p>
                            <p>
                                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                            </p>
                            <p class="reply">
                                <a href="#"><i class="fa fa-reply"></i> Reply</a>
                            </p>
                        </div>

                    </div>
                    <!-- /.comment -->
                </div>
                <!-- /#comments -->


                <div id="comment-form">

                    <h4 class="text-uppercase">Leave comment</h4>

                    <form>
                        <div class="row">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name">
                                        Name <span class="required">*</span>
                                    </label>
                                    <input type="text" class="form-control" id="name">
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">
                                        Email <span class="required">*</span>
                                    </label>
                                    <input type="text" class="form-control" id="email">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="comment">
                                        Comment <span class="required">*</span>
                                    </label>
                                    <textarea class="form-control" id="comment" rows="4"></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 text-right">
                                <button class="btn btn-template-main"><i class="fa fa-comment-o"></i> Post comment</button>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- /#comment-form -->

            </div>
            <!-- /#blog-post -->
            <!-- *** LEFT COLUMN END *** -->

        </div>
    </div>
</div>

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Ads/Edit.cshtml
@using PawGuide.Web
@model AdDetailsServiceModel

@{
    ViewData["Title"] = "Edit Ad";
}

@await Html.PartialAsync("_HeadingPartial")

<script src="https://cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>

<div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form method="post">
            <h3>Edit This Ad</h3>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicUrl"></label>
                <input asp-for="PicUrl" class="form-control" />
                <span asp-validation-for="PicUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" rows="30" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            @if (User.IsInRole(WebConstants.ModeratorRole) || User.IsInRole(WebConstants.AdministratorRole))
            {
                <div class="form-group">
                    <label asp-for="IsApproved"></label>
                    @Html.RadioButtonFor(m => m.IsApproved, true) Yes
                    @Html.RadioButtonFor(m => m.IsApproved, false) No
                    <span asp-validation-for="IsApproved" class="text-danger"></span>
                </div>
            }
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
<script>
    CKEDITOR.replace('Content');
</script>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

}

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Ads/ForApproval.cshtml
@model AdListingViewModel

@{
    ViewData["Title"] = "Ads for Approvel";
}

@await Html.PartialAsync("_HeadingPartial")

<div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Pic
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var ad in Model.Ads)
                {
                    if (ad.IsApproved == false)
                    {
                        <tr>
                            <th>
                                <a asp-area="Publications" asp-controller="Ads" asp-action="Edit" asp-route-id="@ad.Id" asp-route-title="@ad.Title.ToFriendlyUrl()">@ad.Title</a>
                            </th>
                            <th>
                                <div class="col-md-2 image">
                                    <img src="@ad.PicUrl" class="img-responsive" alt="@ad.Title" />
                                </div>
                            </th>
                        </tr>
                    }
                }
            </tbody>
        </table>

        @if (Model.TotalPublications > Model.Ads.Count())
        {
            <ul class="pagination">
                <li class="@(Model.CurrentPage == 1 ? "disabled" : string.Empty)">
                    <a asp-route-page="@Model.PreviousPage"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty)">
                    <a asp-route-page="@Model.NextPage"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        }

    </div>
    <div class="col-md-2"></div>
</div>

PawGuide.Web/PawGuide.Web/Areas/Publications/Views/Ads/Index.cshtml
@model AdListingViewModel
@{
    ViewData["Title"] = "Ads";
}
@await Html.PartialAsync("_HeadingPartial")

<div id="content">
    <div class="container">
        <div class="row">
            <!-- *** LEFT COLUMN ***
            _________________________________________________________ -->

            <div class="col-md-9" id="blog-listing-medium">
                @foreach (var ad in Model.Ads)
                {

                    if (ad.IsApproved == true || ad.Author == User.Identity.Name)
                    {
                        <section class="post">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="image">
                                        <a asp-action="Details" asp-route-id="@ad.Id" asp-route-title="@ad.Title.ToFriendlyUrl()">
                                            <img src="@ad.PicUrl" class="img-responsive" alt="@ad.Title">
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <h2>
                                        <a asp-action="Details" asp-route-id="@ad.Id" asp-route-title="@ad.Title.ToFriendlyUrl()">
                                            @ad.Title
                                        </a>
                                    </h2>
                                    <div class="clearfix">
                                        <p class="author-category">
                                            By @ad.Author
                                        </p>
                                        <p class="date-comments">
                                            <a href="blog-post.html"><i class="fa fa-calendar-o"></i>@ad.PublishDate.ToShortDateString()</a>
                                            <a href="blog-post.html"><i class="fa fa-comment-o"></i> 8 Comments</a>
                                        </p>
                                    </div>
                                    <p class="intro">
                                        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                        Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                                        @if (ad.IsApproved == false)
                                        {
                                            <img src="https://barmakapproved.files.wordpress.com/2012/07/notapproved.png" />
                                        }
                                    </p>
                                    <p class="read-more">
                                        <a asp-action="Details" asp-route-id="@ad.Id" asp-route-title="@ad.Title.ToFriendlyUrl()" class="btn btn-template-main">Continue reading</a>
                                    </p>
                                </div>
                            </div>
                        </section>
                    }
                }

                @if (Model.TotalPublications > Model.Ads.Count())
                {
                    <ul class="pager">
                        <li class="@(Model.CurrentPage == 1 ? "disabled" : string.Empty)">
                            <a asp-route-page="@Model.PreviousPage" aria-label="Previous">
                                <span aria-hidden="true">
                                    &larr; Older
                                </span>
                            </a>
                        </li>
                        <li class="@(Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty)">
                            <a asp-route-page="@Model.NextPage" aria-label="Next">
                                <span aria-hidden="true">
                                    Newer &rarr;
                                </span>
                            </a>
                        </li>
                    </ul>
                }
            </div>

            <!-- *** LEFT COLUMN END *** -->
        </div>
    </div>
</div>

@*<div class="row">
        <div class="col-md-6">
            <ul class="list-group article-list">
                @foreach (var ad in Model.Ads)
                {
                    if (ad.IsApproved == true || ad.Author == User.Identity.Name)
                    {
                        <li class="list-group-item">
                            <img src="@ad.PicUrl" alt="Sample Image" width="300px" />
                            <a asp-action="Details" asp-route-id="@ad.Id" asp-route-title="@ad.Title.ToFriendlyUrl()">@ad.Title</a>
                            <br />
                            <small>published by @ad.Author on @ad.PublishDate.ToShortDateString()</small>
                            @if (ad.IsApproved == false)
                            {
                                <img src="https://barmakapproved.files.wordpress.com/2012/07/notapproved.png" />
                            }
                        </li>
                    }
                }
            </ul>
        </div>
    </div>*@