PawGuide.Web/PawGuide.Web/Areas/Admin/Models/Users/SearchViewModel.cs
namespace PawGuide.Web.Areas.Admin.Models.Users
{
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Services.Admin.Models;

    public class SearchViewModel
    {
        public IEnumerable<AdminUserListingServiceModel> Users { get; set; }
            = new List<AdminUserListingServiceModel>();

        public IEnumerable<SelectListItem> Roles { get; set; }


        public string SearchText { get; set; }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/BusinessFormViewModel.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using Data.Models;
    using Common.Mapping;
    using Services.Businesses.Models;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.AspNetCore.Http;

    using static Data.DataConstants;

    public class BusinessFormViewModel : IMapFrom<BusinessEditServiceModel>
    {
        [Required]
        [MinLength(UserNameMinLength)]
        [MaxLength(UserNameMaxLength)]
        public string Name { get; set; }

        [Required]
        public TypeBusiness Type { get; set; }

        [MinLength(5)]
        [MaxLength(2000)]
        [Display(Name = "Web Page")]
        public string WebPageUrl { get; set; }

        [Required]
        [MinLength(CityMinLength)]
        [MaxLength(CityMaxLength)]
        public string City { get; set; }

        [Required]
        [MinLength(BusinessAddressMinLength)]
        [MaxLength(BusinessAddressMaxLength)]
        public string Address { get; set; }

        [Display(Name = "Lalatitude")]
        public double LatLocation { get; set; }

        [Display(Name = "Longitude")]
        public double LngLocation { get; set; }

        public bool IsApproved { get; set; }

        [Required]
        [Display(Name = "Pet Types")]
        public IEnumerable<PetType> PetTypes { get; set; }

        public IFormFile Image { get; set; }

        public string Note { get; set; }

        [MinLength(PicUrlMinLength)]
        [MaxLength(PicUrlMaxLength)]
        [Display(Name = "Picture URL")]
        public string PicUrl { get; set; }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/BusinessIndexViewModel.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using System.Collections.Generic;
    using PawGuide.Services.Businesses.Models;

    public class BusinessIndexViewModel : BusinessSearchFormModel
    {
        public IEnumerable<BusinessListingServiceModel> Business { get; set; }

    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/BusinessListingViewModel.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using Data.Models;
    using Services.Businesses.Models;
    using System.Collections.Generic;

    public class BusinessListingViewModel : BusinessSearchFormModel
    {
        public IEnumerable<BusinessListingServiceModel> Businesses { get; set; }

        public TypeBusiness Type (int index)
        {
            var type = (TypeBusiness)index;

            return type;
        }

        public PetType PetType(int index)
        {
            var type = (PetType)index;

            return type;
        }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/BusinessSearchFormModel.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using System.ComponentModel.DataAnnotations;

    public class BusinessSearchFormModel : Pager
    {
        public string SearchText { get; set; }

        [Display(Name = "Search In Businesses")]
        public bool SearchInBusinesses { get; set; } = true;
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/BusinessSearchViewModel.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using System.Collections.Generic;
    using PawGuide.Data.Models;
    using PawGuide.Services.Businesses.Models;

    public class BusinessSearchViewModel
    {
        public IEnumerable<BusinessListingServiceModel> Businesses { get; set; }
            = new List<BusinessListingServiceModel>();

        public TypeBusiness Type(int index)
        {
            var type = (TypeBusiness)index;

            return type;
        }

        public PetType PetType(int index)
        {
            var type = (PetType)index;

            return type;
        }

        public string SearchText { get; set; }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/Pager.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using System;
    using PawGuide.Services;

    public class Pager
    {
        public int TotalBusinesses { get; set; }

        public int TotalPages =>
            (int)Math.Ceiling((double)this.TotalBusinesses / ServiceConstants.BusinessesPageSize);

        public int CurrentPage { get; set; }

        public int PreviousPage => this.CurrentPage <= 1 ? 1 : this.CurrentPage - 1;

        public int NextPage
            => this.CurrentPage == this.TotalPages
                ? this.TotalPages
                : this.CurrentPage + 1;
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Models/Businesses/PublishBusinessFormModel.cs
namespace PawGuide.Web.Areas.Business.Models.Businesses
{
    using Data.Models;
    using Common.Mapping;
    using Services.Businesses.Models;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.AspNetCore.Http;

    using static Data.DataConstants;

    public class PublishBusinessFormModel : IMapFrom<BusinessDetailsServiceModel>
    {
        [Required]
        [MinLength(UserNameMinLength)]
        [MaxLength(UserNameMaxLength)]
        public string Name { get; set; }

        [Required]
        public TypeBusiness Type { get; set; }

        [MinLength(5)]
        [MaxLength(2000)]
        public string WebPageUrl { get; set; }

        [Required]
        [MinLength(CityMinLength)]
        [MaxLength(CityMaxLength)]
        public string City { get; set; }

        [Required]
        [MinLength(BusinessAddressMinLength)]
        [MaxLength(BusinessAddressMaxLength)]
        public string Address { get; set; }

        public double LatLocation { get; set; }

        public double LngLocation { get; set; }

        public bool IsApproved { get; set; }

        public IEnumerable<PetType> PetTypes { get; set; }

        public IFormFile Image { get; set; }

        public string Note { get; set; }

        [MinLength(PicUrlMinLength)]
        [MaxLength(PicUrlMaxLength)]
        public string PicUrl { get; set; }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Controllers/BusinessesController.cs
namespace PawGuide.Web.Areas.Business.Controllers
{
    using AutoMapper;
    using Data.Models;
    using Infrastructure.Extensions;
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PawGuide.Web.Areas.Business.Models.Businesses;
    using Services.Businesses;
    using System.Threading.Tasks;

    using static WebConstants;

    [Area(BusinessArea)]
    [Authorize]
    public class BusinessesController : Controller
    {
        private readonly IBusinessService businesses;
        private readonly UserManager<User> userManager;
        private readonly IMapper mapper;

        public BusinessesController(IBusinessService businesses, 
            UserManager<User> userManager, 
            IMapper mapper)
        {
            this.businesses = businesses;
            this.userManager = userManager;
            this.mapper = mapper;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int page = 1)
            => View(new BusinessListingViewModel
            {
                Businesses = await this.businesses.AllAsync(page),
                TotalBusinesses = await this.businesses.TotalAsync(),
                CurrentPage = page
            });

        [AllowAnonymous]
        public async Task<IActionResult> Search(BusinessSearchFormModel model)
        {
            var viewModel = new BusinessSearchViewModel
            {
                SearchText = model.SearchText
            };

            if (model.SearchInBusinesses)
            {
                viewModel.Businesses = await this.businesses.FindAsync(model.SearchText);
            }

            return View(viewModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> BusinessByType(int type, int page = 1)
            => View(new BusinessListingViewModel
            {
                Businesses = await this.businesses.BusinessTypeAsync(type, page),
                TotalBusinesses = await this.businesses.TotalAsync(),
                CurrentPage = page
            });

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var currentBusiness = await this.businesses.ById(id);

            if (currentBusiness == null)
            {
                return NotFound();
            }

            return View(currentBusiness);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Create(BusinessFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = this.userManager.GetUserId(User);

            var isApproved = false;

            var businessId = await this.businesses.CreateAsync(
                model.Name,
                model.Type,
                model.WebPageUrl,
                model.Address,                 
                model.LatLocation,
                model.LngLocation,
                model.PetTypes,
                model.City,
                model.PicUrl,
                isApproved,
                model.Note,
                userId);


            if (model.Image.HasValidImage())
            {
                var imageName = model.Image.SaveImage(businessId, model.Type.ToString(), model.Name, BusinessImagesPath);
                await this.businesses.SetImage(businessId, imageName);
            }

            this.TempData.AddSuccessMessage(string.Format(SuccessfullAdd, model.Name));

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var businessExists = await this.businesses.Exists(id);

            if (!businessExists)
            {
                return NotFound();
            }

            var businessToEdit = await this.businesses.EditById(id);

            var publishFormModel = this.mapper.Map<BusinessFormViewModel>(businessToEdit);
            
            return this.ViewOrNotFound(publishFormModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, BusinessFormViewModel businessModel)
        {
            if (!ModelState.IsValid)
            {
                return View(businessModel);
            }

            var userId = this.userManager.GetUserId(User);

            if (businessModel.Image.HasValidImage())
            {
                await this.businesses.SetImage(id, businessModel.Image.
                    SaveImage(id, businessModel.Type.ToString(), businessModel.Name, BusinessImagesPath));
            }

            var update = await this.businesses.EditAsync(
                id,
                businessModel.Name,
                businessModel.Type,
                businessModel.WebPageUrl,
                businessModel.Address,
                businessModel.LatLocation,
                businessModel.LngLocation,
                businessModel.PetTypes,
                businessModel.City,
                businessModel.PicUrl,
                businessModel.IsApproved,
                businessModel.Note,
                userId);

            if (!update)
            {
                return this.BadRequest();
            }

            this.TempData.AddWarningMessage(string.Format(SuccessfullEdit, businessModel.Name));


            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllLocations()
            => this.Ok(await this.businesses.AllLocations());


        public async Task<IActionResult> ForApproval(int page = 1)
            => View(new BusinessListingViewModel
            {
                Businesses = await this.businesses.AllAsync(page),
                TotalBusinesses = await this.businesses.TotalAsync(),
                CurrentPage = page
            });

        public async Task<IActionResult> Delete(int id)
        {
            var businessExists = await this.businesses.Exists(id);

            if (!businessExists)
            {
                return NotFound();
            }

            var businessToEdit = await this.businesses.ById(id);

            return this.ViewOrNotFound(businessToEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, string empty)
        {
            var isDeletable = await this.businesses.Exists(id);
            var user = await this.userManager.GetUserAsync(User);

            if (!isDeletable)
            {
                return this.BadRequest();
            }

            this.TempData.AddDangerMessage(SuccessfullDelete);

            await this.businesses.DeleteAsync(id, this.userManager.GetUserId(User), user);

            return RedirectToAction(nameof(Index));
        }
    }
}

PawGuide.Web/PawGuide.Web/Areas/Business/Views/Businesses/BusinessByType.cshtml
@model BusinessListingViewModel
@{
    ViewData["Title"] = "Pet Friendly";
}

@await Html.PartialAsync("_HeadingPartial")

<div id="content">
    <div class="container">
        <div class="row">
            <!-- *** LEFT COLUMN ***
            _________________________________________________________ -->

            <div class="col-md-9" id="blog-listing-small">
                @await Html.PartialAsync("_TypeSelectFormPartial")
                
                <div class="row">

                    @foreach (var business in Model.Businesses)
                    {
                        if (business.IsApproved == true || business.Author == User.Identity.Name)
                        {
                            <div class="col-md-4 col-sm-6">
                                <div class="box-image-text blog">
                                    <div class="top">
                                        <div class="image">
                                            <img src="@business.PicUrl" alt="" class="img-responsive">
                                            @if (business.IsApproved == false)
                                            {
                                                <img src="https://barmakapproved.files.wordpress.com/2012/07/notapproved.png"/>
                                            }
                                        </div>
                                        <div class="bg"></div>
                                        <div class="text">
                                            <p class="buttons">
                                                <a asp-action="Details" asp-route-id="@business.Id" asp-route-title="@business.Name.ToFriendlyUrl()" class="btn btn-template-transparent-primary">
                                                    <i class="fa fa-link"></i>
                                                    Read more
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="content">
                                        <h4>
                                            <a asp-action="Details" asp-route-id="@business.Id" asp-route-title="@business.Name.ToFriendlyUrl()">
                                                @business.Name
                                            </a>
                                        </h4>
                                        <p class="author-category">
                                            By
                                            @business.Author
                                            on
                                            @business.PublishDate.ToShortDateString()
                                        </p>
                                        <p class="text-center">
                                            @{
                                                var businessIndex = business.Type.GetHashCode();
                                                var businessType = Model.Type(businessIndex);
                                                var petIndex = business.PetType.GetHashCode();
                                                var petType = Model.PetType(petIndex);
                                            }

                                            Type of place: @Html.DisplayFor(model => businessType)
                                            <br/>
                                            City: @business.City
                                            <br/>
                                            Pets Alowed: @Html.DisplayFor(model => petType)
                                        </p>
                                        <p class="read-more">
                                            <a asp-action="Details" asp-route-id="@business.Id" asp-route-title="@business.Name.ToFriendlyUrl()" class="btn btn-template-main">
                                                Continue reading
                                            </a>
                                        </p>
                                    </div>
                                </div>
                                <!-- /.box-image-text -->
                            </div>
                        }
                    }

                </div>
                @await Html.PartialAsync("_PagerPartial")

            </div>
            <!-- /.col-md-9 -->
            <!-- *** LEFT COLUMN END *** -->
        </div>
    </div>
</div>

PawGuide.Web/PawGuide.Web/Areas/Business/Views/Businesses/Details.cshtml
@model BusinessDetailsServiceModel
@{
    ViewData["Title"] = Model.Name;
}



<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li>
                        <a asp-area="Business" asp-controller="Businesses" asp-action="Index">Businesses</a>
                    </li>
                    <li>@ViewData["Title"]</li>
                </ul>

            </div>
        </div>
    </div>
</div>

<div id="content">
    <div class="container">

        <div class="row">
            <!-- *** LEFT COLUMN ***
            _________________________________________________________ -->
            <div class="col-md-9" id="blog-post">
                <div id="post-content">
                    <p class="text-center">
                        <img src="@Model.PicUrl" alt="Sample Image" width="300px" />
                    </p>

                    <div class="row text-center">
                        <div class="project-more">
                            <div class="heading">
                                <h3>@ViewData["Title"]</h3>
                            </div>
                            <div class="box">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <tbody>
                                        <tr>
                                            <th>Type</th>
                                            <td>@Html.DisplayFor(model => model.Type)</td>
                                        </tr>
                                        <tr>
                                            <th>City</th>
                                            <td>@Model.City</td>
                                        </tr>
                                        <tr>
                                            <th>Address</th>
                                            <td>@Model.Address</td>
                                        </tr>
                                        <tr>
                                            <th>Pets Allowed</th>
                                            <td>@Model.PetType</td>
                                        </tr>
                                        <tr>
                                            <th>Notes</th>
                                            <td>@Model.Note</td>
                                        </tr>
                                        <tr>
                                            <th>Latitude</th>
                                            <td>@Model.LatLocation</td>
                                        </tr>
                                        <tr>
                                            <th>Longitude</th>
                                            <td>@Model.LngLocation</td>
                                        </tr>
                                        <tr>
                                            <th>Web Page</th>
                                            <td><a href="@Model.WebPageUrl">@Model.WebPageUrl</a></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="text-muted text-uppercase mb-small text-right">
                        <em>By @Model.Author | @Model.PublishDate.ToShortDateString()</em>
                    </p>

                    <div class="row">
                        <div class="col-sm-12 text-center">
                            @if (User.Identity.IsAuthenticated && User.Identity.Name.Equals(Model.Author) || User.IsInRole(WebConstants.AdministratorRole))
                            {
                                <a class="btn btn-sm btn-primary" asp-area="Business" asp-controller="Businesses" asp-action="Edit" asp-route-id="@Model.Id" asp-route-title="@Model.Name.ToFriendlyUrl()">Edit</a>
                                <a class="btn btn-sm btn-danger" asp-area="Business" asp-controller="Businesses" asp-action="Delete" asp-route-id="@Model.Id" asp-route-title="@Model.Name.ToFriendlyUrl()">Delete</a>
                            }
                        </div>
                    </div>
                </div>
                <!-- /#post-content -->

                <div id="comments">
                    <h4 class="text-uppercase">2 comments</h4>


                    <div class="row comment">
                        <div class="col-sm-3 col-md-2 text-center-xs">
                            <p>
                                <img src="img/blog-avatar2.jpg" class="img-responsive img-circle" alt="">
                            </p>
                        </div>
                        <div class="col-sm-9 col-md-10">
                            <h5 class="text-uppercase">Julie Alma</h5>
                            <p class="posted">
                                <i class="fa fa-clock-o"></i> September 23, 2011 at 12:00 am
                            </p>
                            <p>
                                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                            </p>
                            <p class="reply">
                                <a href="#"><i class="fa fa-reply"></i> Reply</a>
                            </p>
                        </div>
                    </div>
                    <!-- /.comment -->


                    <div class="row comment last">

                        <div class="col-sm-3 col-md-2 text-center-xs">
                            <p>
                                <img src="img/blog-avatar.jpg" class="img-responsive img-circle" alt="">
                            </p>
                        </div>

                        <div class="col-sm-9 col-md-10">
                            <h5 class="text-uppercase">Louise Armero</h5>
                            <p class="posted">
                                <i class="fa fa-clock-o"></i> September 23, 2012 at 12:00 am
                            </p>
                            <p>
                                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
                                Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                            </p>
                            <p class="reply">
                                <a href="#"><i class="fa fa-reply"></i> Reply</a>
                            </p>
                        </div>

                    </div>
                    <!-- /.comment -->
                </div>
                <!-- /#comments -->


                <div id="comment-form">

                    <h4 class="text-uppercase">Leave comment</h4>

                    <form>
                        <div class="row">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name">
                                        Name <span class="required">*</span>
                                    </label>
                                    <input type="text" class="form-control" id="name">
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">
                                        Email <span class="required">*</span>
                                    </label>
                                    <input type="text" class="form-control" id="email">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="comment">
                                        Comment <span class="required">*</span>
                                    </label>
                                    <textarea class="form-control" id="comment" rows="4"></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 text-right">
                                <button class="btn btn-template-main"><i class="fa fa-comment-o"></i> Post comment</button>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- /#comment-form -->

            </div>
            <!-- /#blog-post -->
            <!-- *** LEFT COLUMN END *** -->

        </div>
    </div>
</div>      

PawGuide.Web/PawGuide.Web/Areas/Business/Views/Businesses/ForApproval.cshtml
@model BusinessListingViewModel

@{
    ViewData["Title"] = "Businesses for Approvel";
}

@await Html.PartialAsync("_HeadingPartial")

<div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Type
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var business in Model.Businesses)
                {
                    if (business.IsApproved == false)
                    {
                        <tr>
                            <th>
                                <a asp-area="Business" asp-controller="Businesses" asp-action="Edit" asp-route-id="@business.Id" asp-route-title="@business.Name.ToFriendlyUrl()">@business.Name</a>
                            </th>
                            <th>
                                @business.Type
                            </th>
                        </tr>
                    }
                }
            </tbody>
        </table>

        @if (Model.TotalBusinesses > Model.Businesses.Count())
        {
            <ul class="pagination">
                <li class="@(Model.CurrentPage == 1 ? "disabled" : string.Empty)">
                    <a asp-route-page="@Model.PreviousPage"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty)">
                    <a asp-route-page="@Model.NextPage"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        }

    </div>
    <div class="col-md-2"></div>
</div>

PawGuide.Web/PawGuide.Web/Areas/Business/Views/Businesses/ForApprovel.cshtml
@model BusinessListingViewModel

@{
    ViewData["Title"] = "Businesses for Approvel";
}

<h1>@ViewData["Title"]</h1>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Type
        </th>
        <th>
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var business in Model.Businesses)
    {
        if (business.IsApproved == false)
        {
            <tr>
                <th>
                    <a asp-area="Business" asp-controller="Businesses"  asp-action="Edit" asp-route-id="@business.Id" asp-route-title="@business.Name.ToFriendlyUrl()">@business.Name</a>
                </th>
                <th>
                    @business.Type
                </th>
            </tr>
        }
    }
    </tbody>
</table>
@if (Model.TotalBusinesses > Model.Businesses.Count())
{
    <ul class="pagination">
        <li class="@(Model.CurrentPage == 1 ? "disabled" : string.Empty)">
            <a asp-route-page="@Model.PreviousPage"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="@(Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty)">
            <a asp-route-page="@Model.NextPage"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
}